/* tslint:disable */
/* eslint-disable */
/**
 * DressMe API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PingResponse,
} from '../models/index';
import {
    PingResponseFromJSON,
    PingResponseToJSON,
} from '../models/index';

/**
 * PingApi - interface
 * 
 * @export
 * @interface PingApiInterface
 */
export interface PingApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PingApiInterface
     */
    getMessageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PingResponse>>;

    /**
     */
    getMessage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PingResponse>;

}

/**
 * 
 */
export class PingApi extends runtime.BaseAPI implements PingApiInterface {

    /**
     */
    async getMessageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PingResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMessage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PingResponse> {
        const response = await this.getMessageRaw(initOverrides);
        return await response.value();
    }

}
