/* tslint:disable */
/* eslint-disable */
/**
 * DressMe API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returns ping information
 * @export
 * @interface PingResponse
 */
export interface PingResponse {
    /**
     * The message attribute
     * @type {string}
     * @memberof PingResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PingResponse interface.
 */
export function instanceOfPingResponse(value: object): value is PingResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PingResponseFromJSON(json: any): PingResponse {
    return PingResponseFromJSONTyped(json, false);
}

export function PingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function PingResponseToJSON(json: any): PingResponse {
      return PingResponseToJSONTyped(json, false);
  }

  export function PingResponseToJSONTyped(value?: PingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

