/* tslint:disable */
/* eslint-disable */
/**
 * DressMe API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Query response
 * @export
 * @interface QueryResponse
 */
export interface QueryResponse {
    /**
     * The query result
     * @type {string}
     * @memberof QueryResponse
     */
    content: string;
}

/**
 * Check if a given object implements the QueryResponse interface.
 */
export function instanceOfQueryResponse(value: object): value is QueryResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function QueryResponseFromJSON(json: any): QueryResponse {
    return QueryResponseFromJSONTyped(json, false);
}

export function QueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

  export function QueryResponseToJSON(json: any): QueryResponse {
      return QueryResponseToJSONTyped(json, false);
  }

  export function QueryResponseToJSONTyped(value?: QueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

