/* tslint:disable */
/* eslint-disable */
/**
 * DressMe API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The user configuration
 * @export
 * @interface UserResponseConfiguration
 */
export interface UserResponseConfiguration {
    /**
     * 
     * @type {object}
     * @memberof UserResponseConfiguration
     */
    activePlan: object;
    /**
     * 
     * @type {number}
     * @memberof UserResponseConfiguration
     */
    maxCaloriesPerDay: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserResponseConfiguration
     */
    excludedIngredients: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserResponseConfiguration
     */
    intolerances: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UserResponseConfiguration
     */
    lang: string;
}

/**
 * Check if a given object implements the UserResponseConfiguration interface.
 */
export function instanceOfUserResponseConfiguration(value: object): value is UserResponseConfiguration {
    if (!('activePlan' in value) || value['activePlan'] === undefined) return false;
    if (!('maxCaloriesPerDay' in value) || value['maxCaloriesPerDay'] === undefined) return false;
    if (!('excludedIngredients' in value) || value['excludedIngredients'] === undefined) return false;
    if (!('intolerances' in value) || value['intolerances'] === undefined) return false;
    if (!('lang' in value) || value['lang'] === undefined) return false;
    return true;
}

export function UserResponseConfigurationFromJSON(json: any): UserResponseConfiguration {
    return UserResponseConfigurationFromJSONTyped(json, false);
}

export function UserResponseConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'activePlan': json['activePlan'],
        'maxCaloriesPerDay': json['maxCaloriesPerDay'],
        'excludedIngredients': json['excludedIngredients'],
        'intolerances': json['intolerances'],
        'lang': json['lang'],
    };
}

  export function UserResponseConfigurationToJSON(json: any): UserResponseConfiguration {
      return UserResponseConfigurationToJSONTyped(json, false);
  }

  export function UserResponseConfigurationToJSONTyped(value?: UserResponseConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activePlan': value['activePlan'],
        'maxCaloriesPerDay': value['maxCaloriesPerDay'],
        'excludedIngredients': value['excludedIngredients'],
        'intolerances': value['intolerances'],
        'lang': value['lang'],
    };
}

